---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
vagrant:
  raw_config_args:
    - "ssh.insert_key = false"
    # - "vm.network 'forwarded_port', guest: 80, host: 8080"
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 1024
        cpus: 1
platforms:
  - name: centos7
    box: centos/7
    #memory: 1024
    #cpus: 1
    groups:
      - rhel_family

lint:
  name: yamllint
  options:
    config-file: .yamllint
provisioner:
  name: ansible
  log: False
  inventory:
    group_vars:
      rhel_family:
        ansible_python_interpreter: "/usr/bin/python"
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
